# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- demo/*
- alembic-jekyll-theme.gemspec

# 2. Installed Gems
gems:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jemoji

# 3. Gem settings
paginate: 5 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
social: # jekyll-seo-tag > social overrides
  name: Software Synthesis and Hatching | IIT Mandi # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://www.facebook.com/prog.iitmandi/
    - https://github.com/ssh-iitmandi

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Asia/Kolkata # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "My thoughts and ideas" # The post list page content
    feature_text: |
      Welcome to the blog
    feature_image: ""

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page # Default layout
      image: "/assets/default-social-image.png" # Default image for sharing
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post # Default layout
      image: "/assets/default-social-image.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
title: "Software Synthesis and Hatching | IIT Mandi" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logo.svg" # Site logo, also used in jekyll-seo-tag
description: "" # Site description and default description, also used in jekyll-seo-tag
url: "https://ssh-iitmandi.github.io" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/daviddarnes/alembic"
email: "pc@iitmandi.ac.in"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
avatarurl: "" # Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub

# 8. Site navigation
navigation_header:
  Home: /
  Elements: /elements/
  Blog: /blog/
  Categories: /categories/
  Search: /search/
  Fork Alembic: 

navigation_footer:
  Created by David Darnes: 

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  GitHub: https://github.com/ssh-iitmandi
  link: https://ssh-iitmandi.github.io
  RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
  facebook: "#3B5998"
